services:
  # =====================================
  # MongoDB - Banco de dados principal
  # =====================================
  mongodb:
    image: mongo:7.0
    container_name: financeiro_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: financeiro
    volumes:
      - mongodb_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - financeiro_network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # =====================================
  # Redis - Cache e sessões
  # =====================================
  redis:
    image: redis:7.2-alpine
    container_name: financeiro_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass redis123
    volumes:
      - redis_data:/data
    networks:
      - financeiro_network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

# =====================================
# Volumes persistentes
# =====================================
volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local

# =====================================
# Rede personalizada
# =====================================
networks:
  financeiro_network:
    driver: bridge
